import java.util.Map;
import java.util.logging.Logger;

public class SMSSender {

    private static SMSSender controllerInstance = null;
    private static SMSLogs smsLogs;
    final private static Logger logger = Logger.getLogger(SMSSender.class.getName());

    //Made it into a Singleton cause I only need one instance of the controller
    //and the view
    public static SMSSender getInstance(){
        if (controllerInstance == null){
            controllerInstance = new SMSSender();
            smsLogs = new SMSLogs();
        }
        return controllerInstance;
    }

    //checks SMS by providing a map, requests the DB class to insert SMS
    //checks if the SMS entered is REGISTER to reply to the user
    public void sendSMS(SMS sms){
        sms.checkSMS(sms.getSmsMap());
        insertSMS(sms);

        if (sms.getRegister().equals("REGISTER")){
            receiveReplySMS(sms);
        }
    }

    //creates an SMS and displays it to reply to the user
    //requests the reply SMS to insert into the database
    private void receiveReplySMS(SMS sms) {
        SMS replySMS = new SMS(
                sms.getMsisdn(),
                sms.getSender(),
                sms.getRecipient(),
                sms.getShortCode(),
                null,
                "To complete the promo " +
                        "registration, please send " +
                        "Lastname, Firstname to " +
                        sms.getShortCode(),
                sms.getTimestamp(),
                sms.getStatus(),
                sms.getVoucherCode()
        );

        insertSMS(replySMS);
        displaySMS(sms);
    }

    //logs out the reply to the user
    private void displaySMS(SMS sms){
        smsLogs.showResult(sms.getRegister());
    }

    //requests the database to insert the promo
    public void createPromo(Promo promo){
        smsLogs.showResult(DatabaseConnect.getInstance().insertPromo(promo));
    }

    //requests to insert the SMS, entered by the user, into the database
    private void insertSMS(SMS sms){
        DatabaseConnect.getInstance().insertSMS(sms);

        //because varchar cannot be autogenerated in SQL, I have to improvise
        //a function to update the transaction ID of the SMS
        //transactionID = promocode + autogenerated id
        Map<String, Object> idPromo = DatabaseConnect.getInstance().getIdPromo();
        DatabaseConnect.getInstance().updateTransactionID(idPromo);
    }
}
